### ISSUE TITLE
인수인계 작업

### ISSUE THREAD

**Issue by samjo-nyang** [sparcs-kaist/sparcssso#152]
- [x] 밥 사주기
- [x] sso, sso.sysop 메일링 리스트 추가하기
- [x] sso 공용 비번 전달하기
- [x] Github 권한 주기
- [x] Slack 초대하기
- [ ] 웹 관리 도구 알려주기
- [ ] 업데이트 방법 알려주기
- [x] 베타 서버 및 테스트 알려주기
- [ ] 개발 기초 알려주기
- [ ] 프로토콜 알려주기
- [x] 서버 처음부터 다시 구축해보기
